platform :ios, '8.3'
pod "AFNetworking", "~> 2.0"
pod 'AXRatingView', '~> 0.9.7'
pod 'KIImagePager', '~> 2.1.0'
pod 'ECSlidingViewController', '~> 2.0.3'
pod 'EDStarRating'
pod 'THCalendarDatePicker', '~> 1.2.2'
pod 'LTNavigationBar'
pod 'ActionSheetPicker-3.0'
pod 'MagicalRecord', '~> 2.3.0'
pod 'ngrvalidator', '~> 1.3.0'
pod "YandexMoneySDKiOS"
pod 'Parse'
pod 'APParallaxHeader'
pod 'GSKStretchyHeaderView'
pod 'DZNEmptyDataSet'
pod 'MBAutoGrowingTextView', '~> 0.1.0'
pod 'Fabric'
pod 'Crashlytics'
pod 'Typhoon'
pod 'NanoFrame'
pod 'PFNavigationDropdownMenu'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'PSICommonUtils', :git => 'https://github.com/qntxor/PSICommonUtils.git'
